### ================================================================
### TrakCare HL7 Inbound
###
### 1. Build the payload:  python requests/build_hl7.py [a28|a01|a03|oru]
### 2. Edit the < line below to point to the desired file
### 3. Send
### ================================================================

@tcBaseUrl = {{{{$dotenv CENTRAL_URL}}}}
@authUser  = {{$dotenv CENTRAL_API_USERNAME}}
@authPass  = {{$dotenv CENTRAL_API_PASSWORD}}
@auth      = Basic {{authUser}} {{authPass}}

###
GET {{tcBaseUrl}}/demo01/tcoffline/getData
Authorization: {{auth}}

###
GET {{tcBaseUrl}}/demo01/tcoffline/getDataTest
Authorization: {{auth}}

###
POST {{tcBaseUrl}}/hl7inbound
Authorization: {{auth}}
Content-Type: application/json

< ./hl7_a28.json
